local test = require("santoku.test")
local err = require("santoku.error")
local assert = err.assert
local ivec = require("santoku.ivec")
local dvec = require("santoku.dvec")
local csr = require("santoku.csr")
require("santoku.cvec")
local tbl = require("santoku.table")
local teq = tbl.equals

test("csr.from_cvec / csr.to_cvec roundtrip", function ()
  local n_samples = 3
  local n_features = 4
  local offsets = ivec.create({ 0, 2, 3, 5 })
  local neighbors = ivec.create({ 0, 2, 1, 0, 3 })
  local bitmap = csr.to_cvec(offsets, neighbors, n_samples, n_features)
  local offsets2, neighbors2 = csr.from_cvec(bitmap, n_samples, n_features)
  assert(offsets2:size() == n_samples + 1)
  assert(offsets2:get(0) == 0)
  assert(offsets2:get(1) == 2)
  assert(offsets2:get(2) == 3)
  assert(offsets2:get(3) == 5)
  assert(teq(neighbors2:table(), { 0, 2, 1, 0, 3 }))
  local bitmap2 = csr.to_cvec(offsets2, neighbors2, n_samples, n_features)
  assert(bitmap2:size() == bitmap:size())
end)

test("csr.to_cvec flip_interleave", function ()
  local n_samples = 2
  local n_features = 3
  local offsets = ivec.create({ 0, 2, 3 })
  local neighbors = ivec.create({ 0, 1, 2 })
  local bitmap = csr.to_cvec(offsets, neighbors, n_samples, n_features, true)
  assert(bitmap ~= nil)
end)

test("csr.from_dvec / csr.to_dvec roundtrip", function ()
  local n_samples = 2
  local n_features = 3
  local dense = dvec.create({ 1.0, 0.0, 3.0, 0.0, 2.0, 0.0 })
  local offsets, neighbors, values = csr.from_dvec(dense, n_samples, n_features)
  assert(offsets:size() == n_samples + 1)
  assert(offsets:get(0) == 0)
  assert(offsets:get(1) == 2)
  assert(offsets:get(2) == 3)
  assert(teq(neighbors:table(), { 0, 2, 1 }))
  assert(values:get(0) == 1.0)
  assert(values:get(1) == 3.0)
  assert(values:get(2) == 2.0)
  local dense2 = csr.to_dvec(offsets, neighbors, values, n_samples, n_features)
  assert(teq(dense2:table(), dense:table()))
  local binary = csr.to_dvec(offsets, neighbors, nil, n_samples, n_features)
  assert(teq(binary:table(), { 1.0, 0.0, 1.0, 0.0, 1.0, 0.0 }))
end)

test("csr.extend", function ()
  local off1 = ivec.create({ 0, 2, 3 })
  local nbr1 = ivec.create({ 0, 1, 2 })
  local off2 = ivec.create({ 0, 1, 2 })
  local nbr2 = ivec.create({ 0, 1 })
  local out_off, out_nbr = csr.extend(off1, nbr1, off2, nbr2, 3)
  assert(out_off:size() == 3)
  assert(teq(out_nbr:table(), { 0, 1, 3, 2, 4 }))
end)

test("csr.select", function ()
  local offsets = ivec.create({ 0, 3, 5 })
  local neighbors = ivec.create({ 0, 1, 2, 1, 3 })
  local remap = ivec.create({ 1, 3 })
  local new_off, new_nbr = csr.select(offsets, neighbors, remap)
  assert(new_off:size() == 3)
  assert(new_off:get(0) == 0)
  assert(new_off:get(1) == 1)
  assert(new_off:get(2) == 3)
  assert(teq(new_nbr:table(), { 0, 0, 1 }))
end)

test("csr.seq_select", function ()
  local tokens = ivec.create({ 5, 3, 1, 3, 5 })
  local offsets = ivec.create({ 0, 3, 5 })
  local keep = ivec.create({ 3, 5 })
  local new_tok, new_off = csr.seq_select(tokens, offsets, keep)
  assert(new_off:size() == 3)
  assert(teq(new_tok:table(), { 1, 0, 0, 1 }))
end)

test("csr.seq_select with values", function ()
  local tokens = ivec.create({ 5, 3, 1, 3, 5 })
  local offsets = ivec.create({ 0, 3, 5 })
  local keep = ivec.create({ 3, 5 })
  local vals = dvec.create({ 1.0, 2.0, 3.0, 4.0, 5.0 })
  local new_tok, new_off, new_val = csr.seq_select(tokens, offsets, keep, vals)
  assert(new_off:size() == 3)
  assert(teq(new_tok:table(), { 1, 0, 0, 1 }))
  assert(new_val:get(0) == 1.0)
  assert(new_val:get(1) == 2.0)
  assert(new_val:get(2) == 4.0)
  assert(new_val:get(3) == 5.0)
end)

test("csr.merge", function ()
  local off1 = ivec.create({ 0, 2, 3 })
  local nbr1 = ivec.create({ 1, 3, 2 })
  local off2 = ivec.create({ 0, 1, 3 })
  local nbr2 = ivec.create({ 2, 1, 4 })
  local out_off, out_nbr = csr.merge(off1, nbr1, off2, nbr2)
  assert(out_off:size() == 3)
  assert(teq(out_nbr:table(), { 1, 2, 3, 1, 2, 4 }))
end)

test("csr.subsample", function ()
  local offsets = ivec.create({ 0, 2, 4, 6 })
  local neighbors = ivec.create({ 10, 20, 30, 40, 50, 60 })
  local ids = ivec.create({ 0, 2 })
  local new_off, new_nbr = csr.subsample(offsets, neighbors, ids)
  assert(new_off:size() == 3)
  assert(new_off:get(0) == 0)
  assert(new_off:get(1) == 2)
  assert(new_off:get(2) == 4)
  assert(teq(new_nbr:table(), { 10, 20, 50, 60 }))
end)

test("csr.transpose", function ()
  local offsets = ivec.create({ 0, 2, 3, 5 })
  local tokens = ivec.create({ 0, 1, 1, 0, 2 })
  local csc_off, csc_rows = csr.transpose(offsets, tokens, 3, 3)
  assert(csc_off:size() == 4)
  assert(csc_off:get(0) == 0)
  assert(csc_off:get(1) == 2)
  assert(csc_off:get(2) == 4)
  assert(csc_off:get(3) == 5)
  assert(teq(csc_rows:table(), { 0, 2, 0, 1, 2 }))
end)

test("csr.transpose with values", function ()
  local offsets = ivec.create({ 0, 2, 3 })
  local tokens = ivec.create({ 0, 1, 0 })
  local values = dvec.create({ 1.0, 2.0, 3.0 })
  local csc_off, csc_rows, csc_vals = csr.transpose(offsets, tokens, 2, 2, values)
  assert(csc_off:size() == 3)
  assert(teq(csc_rows:table(), { 0, 1, 0 }))
  assert(csc_vals:get(0) == 1.0)
  assert(csc_vals:get(1) == 3.0)
  assert(csc_vals:get(2) == 2.0)
end)

test("csr.complement", function ()
  local subset = ivec.create({ 1, 3 })
  local comp = csr.complement(subset, 5)
  assert(teq(comp:table(), { 0, 2, 4 }))
end)

test("csr.sort_desc", function ()
  local off = ivec.create({ 0, 3, 5 })
  local nbr = ivec.create({ 0, 1, 2, 3, 4 })
  local sco = dvec.create({ 1.0, 3.0, 2.0, 5.0, 4.0 })
  local sorted_nbr, sorted_sco = csr.sort_desc(off, nbr, sco)
  assert(sorted_nbr:get(0) == 1)
  assert(sorted_nbr:get(1) == 2)
  assert(sorted_nbr:get(2) == 0)
  assert(sorted_sco:get(0) == 3.0)
  assert(sorted_sco:get(1) == 2.0)
  assert(sorted_sco:get(2) == 1.0)
  assert(sorted_nbr:get(3) == 3)
  assert(sorted_nbr:get(4) == 4)
end)

test("csr.sample_select", function ()
  local offsets = ivec.create({ 0, 2, 4, 6, 8 })
  local neighbors = ivec.create({ 0, 5, 0, 3, 5, 7, 3, 7 })
  local ids = ivec.create({ 0, 2 })
  local new_off, new_nbr, local_feats, n_local = csr.sample_select(offsets, neighbors, ids, 10)
  assert(new_off:size() == 3)
  assert(new_off:get(0) == 0)
  assert(new_off:get(1) == 2)
  assert(new_off:get(2) == 4)
  assert(n_local == 3)
  assert(local_feats:size() == 3)
  assert(teq(local_feats:table(), { 0, 5, 7 }))
  assert(new_nbr:get(0) == 0)
  assert(new_nbr:get(1) == 1)
  assert(new_nbr:get(2) == 1)
  assert(new_nbr:get(3) == 2)
end)

test("csr.top_idf basic", function ()
  local offsets = ivec.create({ 0, 3, 6, 8, 10 })
  local neighbors = ivec.create({ 0, 1, 2, 0, 1, 3, 0, 2, 0, 3 })
  local top_features, weights = csr.top_idf(offsets, neighbors, 5, 3)
  assert(top_features:size() == 3)
  assert(weights:size() == 3)
  local w = weights:table()
  assert(w[1] >= w[2] and w[2] >= w[3])
end)

test("csr.top_bns with labels", function ()
  local n_features = 4
  local n_classes = 2
  local f_off = ivec.create({})
  local f_nbr = ivec.create({})
  f_off:push(0)
  f_nbr:push(0); f_nbr:push(1); f_off:push(2)
  f_nbr:push(0); f_nbr:push(1); f_off:push(4)
  f_nbr:push(0); f_nbr:push(1); f_off:push(6)
  f_nbr:push(2); f_nbr:push(3); f_off:push(8)
  f_nbr:push(2); f_nbr:push(3); f_off:push(10)
  f_nbr:push(2); f_nbr:push(3); f_off:push(12)
  local l_off = ivec.create({ 0, 1, 2, 3, 4, 5, 6 })
  local l_nbr = ivec.create({ 0, 0, 0, 1, 1, 1 })
  local top_features, weights = csr.top_bns(f_off, f_nbr, l_off, l_nbr, n_features, n_classes, nil, 2, "max")
  assert(top_features:size() == 2)
  assert(weights:size() == 2)
end)

test("csr.top_chi2 with labels", function ()
  local n_features = 4
  local n_classes = 2
  local f_off = ivec.create({})
  f_off:push(0)
  local f_nbr = ivec.create({})
  f_nbr:push(0); f_nbr:push(1); f_off:push(2)
  f_nbr:push(0); f_off:push(3)
  f_nbr:push(1); f_off:push(4)
  f_nbr:push(2); f_nbr:push(3); f_off:push(6)
  local l_off = ivec.create({ 0, 1, 2, 3, 4 })
  local l_nbr = ivec.create({ 0, 0, 1, 1 })
  local top_features, weights = csr.top_chi2(f_off, f_nbr, l_off, l_nbr, n_features, n_classes, nil, 2, "max")
  assert(top_features:size() == 2)
  assert(weights:size() == 2)
end)
