#undef tk_umap_begin
#undef tk_umap_clear
#undef tk_umap_del
#undef tk_umap_destroy
#undef tk_umap_destroy_key
#undef tk_umap_destroy_value
#undef tk_umap_end
#undef tk_umap_eq
#undef tk_umap_err
#undef tk_umap_exist
#undef tk_umap_get
#undef tk_umap_hash
#undef tk_umap_key
#undef tk_umap_mt
#undef tk_umap_name
#undef tk_umap_pfx
#undef tk_umap_put
#undef tk_umap_resize
#undef tk_umap_size
#undef tk_umap_t
#undef tk_umap_type
#undef tk_umap_value
#undef tk_umap_pushkey
#undef tk_umap_pushvalue
#undef tk_umap_peekkey
#undef tk_umap_peekvalue
